# This is a basic workflow to help you get started with Actions

name: BuildAll

# Controls when the workflow will run
on: push

jobs:
  # Visual Studio build - Windows only
  build-vs:
    strategy:
      matrix:
        vs-version:
          - 2019
          - 2022
        vs-config:
          - Debug
          # - Profile
          # - Release
        vs-platform:
          - win32
          - x64

    runs-on:
      - windows-${{matrix.vs-version}}

    steps:
      - uses: actions/checkout@v4
      - uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: ${{matrix.vs-platform}}
      - name: Setup
        run: ./setup.bat
      - name: Build
        run: msbuild code\build\windows\vs${{matrix.vs-version}}\orx.sln -t:rebuild -property:Configuration=${{matrix.vs-config}}
