name: BuildAll
on: push
jobs:
  # Visual Studio - Windows only
  build-vs:
    strategy:
      matrix:
        vs-version:
          # - 2017
          # - 2019
          - 2022
        vs-config:
          - Debug
          # - Profile
          # - Release
        vs-platform:
          # - x86
          - x64

    runs-on:
      - windows-${{matrix.vs-version}}
      
    # defaults:
    #   run:
    #     shell: cmd

    steps:
      - uses: actions/checkout@v4
      - uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: ${{matrix.vs-platform}}
      - name: Set ORX environment variable
        run: echo ORX=%CD%\code>> %GITHUB_ENV%
        shell: cmd
      - name: Setup
        run: ./setup.bat
      - name: Build engine
        run: msbuild code\build\windows\vs${{matrix.vs-version}}\orx.sln -m -t:rebuild -property:Configuration=${{matrix.vs-config}}
      - name: Build tutorials
        run: msbuild tutorial\build\windows\vs${{matrix.vs-version}}\tutorial.sln -m -t:rebuild -property:Configuration=${{matrix.vs-config}}
      - name: Create project
        run: ./init.bat test
      - name: Build project
        run: msbuild test\build\windows\vs${{matrix.vs-version}}\test.sln -m -t:rebuild -property:Configuration=${{matrix.vs-config}}
      - name: Build core
        run: msbuild code\build\windows\vs${{matrix.vs-version}}\orx.sln -m -t:rebuild "-property:Configuration=Core ${{matrix.vs-config}}"
      - name: Build tool - orxCrypt
        run: msbuild tools\orxCrypt\build\windows\vs${{matrix.vs-version}}\orxCrypt.sln -m -t:rebuild -property:Configuration=${{matrix.vs-config}}
      - name: Build tool - orxFontGen
        run: msbuild tools\orxFontGen\build\windows\vs${{matrix.vs-version}}\orxFontGen.sln -m -t:rebuild -property:Configuration=${{matrix.vs-config}}
