# This is a basic workflow to help you get started with Actions

name: BuildAll

# Controls when the workflow will run
on: push

jobs:
  # Visual Studio build - Windows only
  build-vs:
    runs-on: windows-latest
    strategy:
      matrix:
        vs-version:
          - 2019
          - 2022
        vs-config:
          - Debug
          # - Profile
          # - Release
        vs-platform:
          - x86
          - x64

    steps:
      - name: Map VS year to MSVC version
        shell: bash
        run: |
          if [ "${{ matrix.vs-version }}" == "2017" ]; then
            echo "msvc_version=[15.0, 16.0)" >> $GITHUB_ENV
          elif [ "${{ matrix.vs-version }}" == "2019" ]; then
            echo "msvc_version=[16.0, 17.0)" >> $GITHUB_ENV
          elif [ "${{ matrix.vs-version }}" == "2022" ]; then
            echo "msvc_version=[17.0, 18.0)" >> $GITHUB_ENV
          fi
      - uses: actions/checkout@v4
      - uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: ${{matrix.vs-platform}}
          vs-version: ${{env.msvc_version}}
      - name: Setup
        run: ./setup.bat
      - name: Build
        run: msbuild code\build\windows\vs${{matrix.vs-version}}\orx.sln -t:rebuild -property:Configuration=${{matrix.vs-config}}
