# This is a basic workflow to help you get started with Actions

name: BuildAll

# Controls when the workflow will run
on: push

jobs:
  # Visual Studio build - Windows only
  build-vs:
    runs-on: windows-latest
    strategy:
      matrix:
        vsversion:
          - 2017
          - 2019
          - 2022
        vsconfig:
          - Debug
          - Profile
          - Release
        vsplatform:
          - Win32
          - x64

    steps:
      - uses: actions/checkout@v4
      - uses: microsoft/setup-msbuild@v2
      - name: Setup
        run: ./setup.bat
      - name: orx build (msbuild)
        working-directory: ${{ env.GITHUB_WORKSPACE }}
        run: msbuild code\build\windows\vs${{ matrix.vsversion }}\orx.sln
